-- =========================================================
-- Таблица заявок с сайта. Выполните в Supabase → SQL Editor.
-- =========================================================
create table if not exists public.requests (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  name          text not null,
  email         text not null,
  age_group     text,
  exercise_type text,
  plan          text,
  style         text,
  message       text not null,
  theme         text,
  page_url      text,
  user_agent    text,
  status        text not null default 'new'   -- new / in_progress / done
);

-- Включаем защиту на уровне строк
alter table public.requests enable row level security;

-- Анонимные посетители могут только ДОБАВЛЯТЬ заявки (не читать и не менять)
create policy "anyone can submit a request"
  on public.requests for insert
  to anon
  with check (true);

-- Читать заявки может только владелец проекта (через Dashboard / service role)
create policy "owner can read requests"
  on public.requests for select
  to authenticated
  using (true);

-- Простая защита от спама: не длиннее 4000 символов
alter table public.requests
  add constraint message_length check (char_length(message) <= 4000);
