-- =========================================================
-- Заявки с сайта «Уроки+».
-- Supabase → SQL Editor → New query → вставить весь файл → Run
-- Скрипт можно запускать повторно — он ничего не сломает.
-- =========================================================

-- 1. Таблица -------------------------------------------------
create table if not exists public.requests (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),

  -- данные из формы
  name          text not null,
  email         text not null,
  age_group     text,            -- Дошкольники / Начальная школа / ...
  exercise_type text,            -- Викторина / Найди пару / Своя идея ...
  plan          text,            -- Простое / Стандарт / Комплекс
  style         text,            -- Светлое / Тёмное / Красочное / Свой вариант
  message       text not null,   -- описание задачи или идея

  -- служебное
  theme         text,            -- какая тема сайта была включена
  page_url      text,
  user_agent    text,
  ip            text,

  -- для вашей работы с заявками
  status        text not null default 'new',   -- new / in_progress / done / rejected
  price         integer,                       -- согласованная цена, ₽
  notes         text,                          -- ваши заметки

  constraint requests_message_len check (char_length(message) between 1 and 4000),
  constraint requests_name_len    check (char_length(name) between 1 and 120),
  constraint requests_email_fmt   check (email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$'),
  constraint requests_status_chk  check (status in ('new','in_progress','done','rejected'))
);

create index if not exists requests_created_at_idx on public.requests (created_at desc);
create index if not exists requests_status_idx     on public.requests (status);

-- 2. Безопасность (RLS) ---------------------------------------
alter table public.requests enable row level security;

drop policy if exists "anyone can submit a request" on public.requests;
drop policy if exists "owner can read requests"     on public.requests;
drop policy if exists "anon insert"                 on public.requests;
drop policy if exists "authenticated read"          on public.requests;
drop policy if exists "authenticated update"        on public.requests;

-- Посетители сайта (anon-ключ) могут ТОЛЬКО добавлять заявки.
-- Читать, менять и удалять анонимно нельзя.
create policy "anon insert" on public.requests
  for insert to anon
  with check (true);

-- Вы (вход в Dashboard / service_role) видите и правите всё.
-- service_role обходит RLS автоматически; политика ниже — для
-- случая, если вы сделаете себе логин в проекте.
create policy "authenticated read" on public.requests
  for select to authenticated using (true);
create policy "authenticated update" on public.requests
  for update to authenticated using (true) with check (true);

-- 3. Удобное представление для просмотра ----------------------
create or replace view public.requests_inbox as
  select id, created_at, status, name, email, age_group, exercise_type, plan, style,
         left(message, 120) as preview, price
  from public.requests
  order by created_at desc;

-- 4. (Необязательно) Уведомление на почту через Database Webhook:
--    Database → Webhooks → Create: table requests, event INSERT →
--    HTTP POST на любой сервис (Make, Zapier, n8n, Telegram-бот).


-- 5. Обновление 2026-09: форма из 3 полей (имя, контакт, тема)
--    Если база уже создавалась ранее — запустите этот файл ещё раз:
--    добавится поле contact, email станет необязательным. Ничего не сломается.
alter table public.requests add column if not exists contact text;
alter table public.requests alter column email drop not null;
alter table public.requests drop constraint if exists requests_email_fmt;
alter table public.requests add constraint requests_email_fmt
  check (email is null or email ~* '^[^\s@]+@[^\s@]+\.[^\s@]+$');

-- Вид обновлён: контакт (телефон/Telegram/email) в первой колонке
create or replace view public.requests_inbox as
  select id, created_at, status, name, coalesce(contact, email) as contact, email,
         age_group, exercise_type, plan, style, left(message, 120) as preview, price
  from public.requests
  order by created_at desc;
